title: Mario Perales
#logo:
description: PMP-certified Data Analyst | Excel Automation | Power BI | SQL | Turning complex data into clear, actionable insights for smarter decisions.
#show_download: true
theme: jekyll-theme-minimal

